// Full list of countries with dial codes, flags, and example phone placeholders
export const COUNTRY_CODES = [
  { name: "Afghanistan", iso2: "AF", code: "+93", flag: "🇦🇫", placeholder: "Phone number" },
  { name: "Albania", iso2: "AL", code: "+355", flag: "🇦🇱", placeholder: "Phone number" },
  { name: "Algeria", iso2: "DZ", code: "+213", flag: "🇩🇿", placeholder: "Phone number" },
  { name: "Andorra", iso2: "AD", code: "+376", flag: "🇦🇩", placeholder: "Phone number" },
  { name: "Angola", iso2: "AO", code: "+244", flag: "🇦🇴", placeholder: "Phone number" },
  { name: "Antigua and Barbuda", iso2: "AG", code: "+1268", flag: "🇦🇬", placeholder: "Phone number" },
  { name: "Argentina", iso2: "AR", code: "+54", flag: "🇦🇷", placeholder: "Phone number" },
  { name: "Armenia", iso2: "AM", code: "+374", flag: "🇦🇲", placeholder: "Phone number" },
  { name: "Australia", iso2: "AU", code: "+61", flag: "🇦🇺", placeholder: "4XX XXX XXX" },
  { name: "Austria", iso2: "AT", code: "+43", flag: "🇦🇹", placeholder: "Phone number" },
  { name: "Azerbaijan", iso2: "AZ", code: "+994", flag: "🇦🇿", placeholder: "Phone number" },
  { name: "Bahamas", iso2: "BS", code: "+1242", flag: "🇧🇸", placeholder: "Phone number" },
  { name: "Bahrain", iso2: "BH", code: "+973", flag: "🇧🇭", placeholder: "Phone number" },
  { name: "Bangladesh", iso2: "BD", code: "+880", flag: "🇧🇩", placeholder: "Phone number" },
  { name: "Barbados", iso2: "BB", code: "+1246", flag: "🇧🇧", placeholder: "Phone number" },
  { name: "Belarus", iso2: "BY", code: "+375", flag: "🇧🇾", placeholder: "Phone number" },
  { name: "Belgium", iso2: "BE", code: "+32", flag: "🇧🇪", placeholder: "Phone number" },
  { name: "Belize", iso2: "BZ", code: "+501", flag: "🇧🇿", placeholder: "Phone number" },
  { name: "Benin", iso2: "BJ", code: "+229", flag: "🇧🇯", placeholder: "Phone number" },
  { name: "Bhutan", iso2: "BT", code: "+975", flag: "🇧🇹", placeholder: "Phone number" },
  { name: "Bolivia", iso2: "BO", code: "+591", flag: "🇧🇴", placeholder: "Phone number" },
  { name: "Bosnia and Herzegovina", iso2: "BA", code: "+387", flag: "🇧🇦", placeholder: "Phone number" },
  { name: "Botswana", iso2: "BW", code: "+267", flag: "🇧🇼", placeholder: "Phone number" },
  { name: "Brazil", iso2: "BR", code: "+55", flag: "🇧🇷", placeholder: "Phone number" },
  { name: "Brunei", iso2: "BN", code: "+673", flag: "🇧🇳", placeholder: "Phone number" },
  { name: "Bulgaria", iso2: "BG", code: "+359", flag: "🇧🇬", placeholder: "Phone number" },
  { name: "Burkina Faso", iso2: "BF", code: "+226", flag: "🇧🇫", placeholder: "Phone number" },
  { name: "Burundi", iso2: "BI", code: "+257", flag: "🇧🇮", placeholder: "Phone number" },
  { name: "Cabo Verde", iso2: "CV", code: "+238", flag: "🇨🇻", placeholder: "Phone number" },
  { name: "Cambodia", iso2: "KH", code: "+855", flag: "🇰🇭", placeholder: "Phone number" },
  { name: "Cameroon", iso2: "CM", code: "+237", flag: "🇨🇲", placeholder: "Phone number" },
  { name: "Canada", iso2: "CA", code: "+1", flag: "🇨🇦", placeholder: "(XXX) XXX-XXXX" },
  { name: "Central African Republic", iso2: "CF", code: "+236", flag: "🇨🇫", placeholder: "Phone number" },
  { name: "Chad", iso2: "TD", code: "+235", flag: "🇹🇩", placeholder: "Phone number" },
  { name: "Chile", iso2: "CL", code: "+56", flag: "🇨🇱", placeholder: "Phone number" },
  { name: "China", iso2: "CN", code: "+86", flag: "🇨🇳", placeholder: "1XX XXXX XXXX" },
  { name: "Colombia", iso2: "CO", code: "+57", flag: "🇨🇴", placeholder: "Phone number" },
  { name: "Comoros", iso2: "KM", code: "+269", flag: "🇰🇲", placeholder: "Phone number" },
  { name: "Congo (Congo-Brazzaville)", iso2: "CG", code: "+242", flag: "🇨🇬", placeholder: "Phone number" },
  { name: "Costa Rica", iso2: "CR", code: "+506", flag: "🇨🇷", placeholder: "Phone number" },
  { name: "Croatia", iso2: "HR", code: "+385", flag: "🇭🇷", placeholder: "Phone number" },
  { name: "Cuba", iso2: "CU", code: "+53", flag: "🇨🇺", placeholder: "Phone number" },
  { name: "Cyprus", iso2: "CY", code: "+357", flag: "🇨🇾", placeholder: "Phone number" },
  { name: "Czechia", iso2: "CZ", code: "+420", flag: "🇨🇿", placeholder: "Phone number" },
  { name: "Democratic Republic of the Congo", iso2: "CD", code: "+243", flag: "🇨🇩", placeholder: "Phone number" },
  { name: "Denmark", iso2: "DK", code: "+45", flag: "🇩🇰", placeholder: "Phone number" },
  { name: "Djibouti", iso2: "DJ", code: "+253", flag: "🇩🇯", placeholder: "Phone number" },
  { name: "Dominica", iso2: "DM", code: "+1767", flag: "🇩🇲", placeholder: "Phone number" },
  { name: "Dominican Republic", iso2: "DO", code: "+1809", flag: "🇩🇴", placeholder: "Phone number" },
  { name: "Ecuador", iso2: "EC", code: "+593", flag: "🇪🇨", placeholder: "Phone number" },
  { name: "Egypt", iso2: "EG", code: "+20", flag: "🇪🇬", placeholder: "Phone number" },
  { name: "El Salvador", iso2: "SV", code: "+503", flag: "🇸🇻", placeholder: "Phone number" },
  { name: "Equatorial Guinea", iso2: "GQ", code: "+240", flag: "🇬🇶", placeholder: "Phone number" },
  { name: "Eritrea", iso2: "ER", code: "+291", flag: "🇪🇷", placeholder: "Phone number" },
  { name: "Estonia", iso2: "EE", code: "+372", flag: "🇪🇪", placeholder: "Phone number" },
  { name: "Eswatini", iso2: "SZ", code: "+268", flag: "🇸🇿", placeholder: "Phone number" },
  { name: "Ethiopia", iso2: "ET", code: "+251", flag: "🇪🇹", placeholder: "Phone number" },
  { name: "Fiji", iso2: "FJ", code: "+679", flag: "🇫🇯", placeholder: "Phone number" },
  { name: "Finland", iso2: "FI", code: "+358", flag: "🇫🇮", placeholder: "Phone number" },
  { name: "France", iso2: "FR", code: "+33", flag: "🇫🇷", placeholder: "X XX XX XX XX" },
  { name: "Gabon", iso2: "GA", code: "+241", flag: "🇬🇦", placeholder: "Phone number" },
  { name: "Gambia", iso2: "GM", code: "+220", flag: "🇬🇲", placeholder: "Phone number" },
  { name: "Georgia", iso2: "GE", code: "+995", flag: "🇬🇪", placeholder: "Phone number" },
  { name: "Germany", iso2: "DE", code: "+49", flag: "🇩🇪", placeholder: "1XX XXXXXXX" },
  { name: "Ghana", iso2: "GH", code: "+233", flag: "🇬🇭", placeholder: "Phone number" },
  { name: "Greece", iso2: "GR", code: "+30", flag: "🇬🇷", placeholder: "Phone number" },
  { name: "Grenada", iso2: "GD", code: "+1473", flag: "🇬🇩", placeholder: "Phone number" },
  { name: "Guatemala", iso2: "GT", code: "+502", flag: "🇬🇹", placeholder: "Phone number" },
  { name: "Guinea", iso2: "GN", code: "+224", flag: "🇬🇳", placeholder: "Phone number" },
  { name: "Guinea-Bissau", iso2: "GW", code: "+245", flag: "🇬🇼", placeholder: "Phone number" },
  { name: "Guyana", iso2: "GY", code: "+592", flag: "🇬🇾", placeholder: "Phone number" },
  { name: "Haiti", iso2: "HT", code: "+509", flag: "🇭🇹", placeholder: "Phone number" },
  { name: "Honduras", iso2: "HN", code: "+504", flag: "🇭🇳", placeholder: "Phone number" },
  { name: "Hungary", iso2: "HU", code: "+36", flag: "🇭🇺", placeholder: "Phone number" },
  { name: "Iceland", iso2: "IS", code: "+354", flag: "🇮🇸", placeholder: "Phone number" },
  { name: "India", iso2: "IN", code: "+91", flag: "🇮🇳", placeholder: "98765 43210" },
  { name: "Indonesia", iso2: "ID", code: "+62", flag: "🇮🇩", placeholder: "Phone number" },
  { name: "Iran", iso2: "IR", code: "+98", flag: "🇮🇷", placeholder: "Phone number" },
  { name: "Iraq", iso2: "IQ", code: "+964", flag: "🇮🇶", placeholder: "Phone number" },
  { name: "Ireland", iso2: "IE", code: "+353", flag: "🇮🇪", placeholder: "Phone number" },
  { name: "Israel", iso2: "IL", code: "+972", flag: "🇮🇱", placeholder: "Phone number" },
  { name: "Italy", iso2: "IT", code: "+39", flag: "🇮🇹", placeholder: "Phone number" },
  { name: "Ivory Coast", iso2: "CI", code: "+225", flag: "🇨🇮", placeholder: "Phone number" },
  { name: "Jamaica", iso2: "JM", code: "+1876", flag: "🇯🇲", placeholder: "Phone number" },
  { name: "Japan", iso2: "JP", code: "+81", flag: "🇯🇵", placeholder: "90 1234 5678" },
  { name: "Jordan", iso2: "JO", code: "+962", flag: "🇯🇴", placeholder: "Phone number" },
  { name: "Kazakhstan", iso2: "KZ", code: "+7", flag: "🇰🇿", placeholder: "Phone number" },
  { name: "Kenya", iso2: "KE", code: "+254", flag: "🇰🇪", placeholder: "Phone number" },
  { name: "Kiribati", iso2: "KI", code: "+686", flag: "🇰🇮", placeholder: "Phone number" },
  { name: "Kosovo", iso2: "XK", code: "+383", flag: "🇽🇰", placeholder: "Phone number" },
  { name: "Kuwait", iso2: "KW", code: "+965", flag: "🇰🇼", placeholder: "Phone number" },
  { name: "Kyrgyzstan", iso2: "KG", code: "+996", flag: "🇰🇬", placeholder: "Phone number" },
  { name: "Laos", iso2: "LA", code: "+856", flag: "🇱🇦", placeholder: "Phone number" },
  { name: "Latvia", iso2: "LV", code: "+371", flag: "🇱🇻", placeholder: "Phone number" },
  { name: "Lebanon", iso2: "LB", code: "+961", flag: "🇱🇧", placeholder: "Phone number" },
  { name: "Lesotho", iso2: "LS", code: "+266", flag: "🇱🇸", placeholder: "Phone number" },
  { name: "Liberia", iso2: "LR", code: "+231", flag: "🇱🇷", placeholder: "Phone number" },
  { name: "Libya", iso2: "LY", code: "+218", flag: "🇱🇾", placeholder: "Phone number" },
  { name: "Liechtenstein", iso2: "LI", code: "+423", flag: "🇱🇮", placeholder: "Phone number" },
  { name: "Lithuania", iso2: "LT", code: "+370", flag: "🇱🇹", placeholder: "Phone number" },
  { name: "Luxembourg", iso2: "LU", code: "+352", flag: "🇱🇺", placeholder: "Phone number" },
  { name: "Madagascar", iso2: "MG", code: "+261", flag: "🇲🇬", placeholder: "Phone number" },
  { name: "Malawi", iso2: "MW", code: "+265", flag: "🇲🇼", placeholder: "Phone number" },
  { name: "Malaysia", iso2: "MY", code: "+60", flag: "🇲🇾", placeholder: "Phone number" },
  { name: "Maldives", iso2: "MV", code: "+960", flag: "🇲🇻", placeholder: "Phone number" },
  { name: "Mali", iso2: "ML", code: "+223", flag: "🇲🇱", placeholder: "Phone number" },
  { name: "Malta", iso2: "MT", code: "+356", flag: "🇲🇹", placeholder: "Phone number" },
  { name: "Marshall Islands", iso2: "MH", code: "+692", flag: "🇲🇭", placeholder: "Phone number" },
  { name: "Mauritania", iso2: "MR", code: "+222", flag: "🇲🇷", placeholder: "Phone number" },
  { name: "Mauritius", iso2: "MU", code: "+230", flag: "🇲🇺", placeholder: "Phone number" },
  { name: "Mexico", iso2: "MX", code: "+52", flag: "🇲🇽", placeholder: "Phone number" },
  { name: "Micronesia", iso2: "FM", code: "+691", flag: "🇫🇲", placeholder: "Phone number" },
  { name: "Moldova", iso2: "MD", code: "+373", flag: "🇲🇩", placeholder: "Phone number" },
  { name: "Monaco", iso2: "MC", code: "+377", flag: "🇲🇨", placeholder: "Phone number" },
  { name: "Mongolia", iso2: "MN", code: "+976", flag: "🇲🇳", placeholder: "Phone number" },
  { name: "Montenegro", iso2: "ME", code: "+382", flag: "🇲🇪", placeholder: "Phone number" },
  { name: "Morocco", iso2: "MA", code: "+212", flag: "🇲🇦", placeholder: "Phone number" },
  { name: "Mozambique", iso2: "MZ", code: "+258", flag: "🇲🇿", placeholder: "Phone number" },
  { name: "Myanmar", iso2: "MM", code: "+95", flag: "🇲🇲", placeholder: "Phone number" },
  { name: "Namibia", iso2: "NA", code: "+264", flag: "🇳🇦", placeholder: "Phone number" },
  { name: "Nauru", iso2: "NR", code: "+674", flag: "🇳🇷", placeholder: "Phone number" },
  { name: "Nepal", iso2: "NP", code: "+977", flag: "🇳🇵", placeholder: "Phone number" },
  { name: "Netherlands", iso2: "NL", code: "+31", flag: "🇳🇱", placeholder: "Phone number" },
  { name: "New Zealand", iso2: "NZ", code: "+64", flag: "🇳🇿", placeholder: "Phone number" },
  { name: "Nicaragua", iso2: "NI", code: "+505", flag: "🇳🇮", placeholder: "Phone number" },
  { name: "Niger", iso2: "NE", code: "+227", flag: "🇳🇪", placeholder: "Phone number" },
  { name: "Nigeria", iso2: "NG", code: "+234", flag: "🇳🇬", placeholder: "Phone number" },
  { name: "North Korea", iso2: "KP", code: "+850", flag: "🇰🇵", placeholder: "Phone number" },
  { name: "North Macedonia", iso2: "MK", code: "+389", flag: "🇲🇰", placeholder: "Phone number" },
  { name: "Norway", iso2: "NO", code: "+47", flag: "🇳🇴", placeholder: "Phone number" },
  { name: "Oman", iso2: "OM", code: "+968", flag: "🇴🇲", placeholder: "Phone number" },
  { name: "Pakistan", iso2: "PK", code: "+92", flag: "🇵🇰", placeholder: "Phone number" },
  { name: "Palau", iso2: "PW", code: "+680", flag: "🇵🇼", placeholder: "Phone number" },
  { name: "Palestine", iso2: "PS", code: "+970", flag: "🇵🇸", placeholder: "Phone number" },
  { name: "Panama", iso2: "PA", code: "+507", flag: "🇵🇦", placeholder: "Phone number" },
  { name: "Papua New Guinea", iso2: "PG", code: "+675", flag: "🇵🇬", placeholder: "Phone number" },
  { name: "Paraguay", iso2: "PY", code: "+595", flag: "🇵🇾", placeholder: "Phone number" },
  { name: "Peru", iso2: "PE", code: "+51", flag: "🇵🇪", placeholder: "Phone number" },
  { name: "Philippines", iso2: "PH", code: "+63", flag: "🇵🇭", placeholder: "Phone number" },
  { name: "Poland", iso2: "PL", code: "+48", flag: "🇵🇱", placeholder: "Phone number" },
  { name: "Portugal", iso2: "PT", code: "+351", flag: "🇵🇹", placeholder: "Phone number" },
  { name: "Qatar", iso2: "QA", code: "+974", flag: "🇶🇦", placeholder: "Phone number" },
  { name: "Romania", iso2: "RO", code: "+40", flag: "🇷🇴", placeholder: "Phone number" },
  { name: "Russia", iso2: "RU", code: "+7", flag: "🇷🇺", placeholder: "Phone number" },
  { name: "Rwanda", iso2: "RW", code: "+250", flag: "🇷🇼", placeholder: "Phone number" },
  { name: "Saint Kitts and Nevis", iso2: "KN", code: "+1869", flag: "🇰🇳", placeholder: "Phone number" },
  { name: "Saint Lucia", iso2: "LC", code: "+1758", flag: "🇱🇨", placeholder: "Phone number" },
  { name: "Saint Vincent and the Grenadines", iso2: "VC", code: "+1784", flag: "🇻🇨", placeholder: "Phone number" },
  { name: "Samoa", iso2: "WS", code: "+685", flag: "🇼🇸", placeholder: "Phone number" },
  { name: "San Marino", iso2: "SM", code: "+378", flag: "🇸🇲", placeholder: "Phone number" },
  { name: "Sao Tome and Principe", iso2: "ST", code: "+239", flag: "🇸🇹", placeholder: "Phone number" },
  { name: "Saudi Arabia", iso2: "SA", code: "+966", flag: "🇸🇦", placeholder: "Phone number" },
  { name: "Senegal", iso2: "SN", code: "+221", flag: "🇸🇳", placeholder: "Phone number" },
  { name: "Serbia", iso2: "RS", code: "+381", flag: "🇷🇸", placeholder: "Phone number" },
  { name: "Seychelles", iso2: "SC", code: "+248", flag: "🇸🇨", placeholder: "Phone number" },
  { name: "Sierra Leone", iso2: "SL", code: "+232", flag: "🇸🇱", placeholder: "Phone number" },
  { name: "Singapore", iso2: "SG", code: "+65", flag: "🇸🇬", placeholder: "9123 4567" },
  { name: "Slovakia", iso2: "SK", code: "+421", flag: "🇸🇰", placeholder: "Phone number" },
  { name: "Slovenia", iso2: "SI", code: "+386", flag: "🇸🇮", placeholder: "Phone number" },
  { name: "Solomon Islands", iso2: "SB", code: "+677", flag: "🇸🇧", placeholder: "Phone number" },
  { name: "Somalia", iso2: "SO", code: "+252", flag: "🇸🇴", placeholder: "Phone number" },
  { name: "South Africa", iso2: "ZA", code: "+27", flag: "🇿🇦", placeholder: "Phone number" },
  { name: "South Korea", iso2: "KR", code: "+82", flag: "🇰🇷", placeholder: "Phone number" },
  { name: "South Sudan", iso2: "SS", code: "+211", flag: "🇸🇸", placeholder: "Phone number" },
  { name: "Spain", iso2: "ES", code: "+34", flag: "🇪🇸", placeholder: "Phone number" },
  { name: "Sri Lanka", iso2: "LK", code: "+94", flag: "🇱🇰", placeholder: "Phone number" },
  { name: "Sudan", iso2: "SD", code: "+249", flag: "🇸🇩", placeholder: "Phone number" },
  { name: "Suriname", iso2: "SR", code: "+597", flag: "🇸🇷", placeholder: "Phone number" },
  { name: "Sweden", iso2: "SE", code: "+46", flag: "🇸🇪", placeholder: "Phone number" },
  { name: "Switzerland", iso2: "CH", code: "+41", flag: "🇨🇭", placeholder: "Phone number" },
  { name: "Syria", iso2: "SY", code: "+963", flag: "🇸🇾", placeholder: "Phone number" },
  { name: "Taiwan", iso2: "TW", code: "+886", flag: "🇹🇼", placeholder: "Phone number" },
  { name: "Tajikistan", iso2: "TJ", code: "+992", flag: "🇹🇯", placeholder: "Phone number" },
  { name: "Tanzania", iso2: "TZ", code: "+255", flag: "🇹🇿", placeholder: "Phone number" },
  { name: "Thailand", iso2: "TH", code: "+66", flag: "🇹🇭", placeholder: "Phone number" },
  { name: "Timor-Leste", iso2: "TL", code: "+670", flag: "🇹🇱", placeholder: "Phone number" },
  { name: "Togo", iso2: "TG", code: "+228", flag: "🇹🇬", placeholder: "Phone number" },
  { name: "Tonga", iso2: "TO", code: "+676", flag: "🇹🇴", placeholder: "Phone number" },
  { name: "Trinidad and Tobago", iso2: "TT", code: "+1868", flag: "🇹🇹", placeholder: "Phone number" },
  { name: "Tunisia", iso2: "TN", code: "+216", flag: "🇹🇳", placeholder: "Phone number" },
  { name: "Turkey", iso2: "TR", code: "+90", flag: "🇹🇷", placeholder: "Phone number" },
  { name: "Turkmenistan", iso2: "TM", code: "+993", flag: "🇹🇲", placeholder: "Phone number" },
  { name: "Tuvalu", iso2: "TV", code: "+688", flag: "🇹🇻", placeholder: "Phone number" },
  { name: "Uganda", iso2: "UG", code: "+256", flag: "🇺🇬", placeholder: "Phone number" },
  { name: "Ukraine", iso2: "UA", code: "+380", flag: "🇺🇦", placeholder: "Phone number" },
  { name: "United Arab Emirates", iso2: "AE", code: "+971", flag: "🇦🇪", placeholder: "50 123 4567" },
  { name: "United Kingdom", iso2: "GB", code: "+44", flag: "🇬🇧", placeholder: "7911 123456" },
  { name: "United States", iso2: "US", code: "+1", flag: "🇺🇸", placeholder: "(555) 123-4567" },
  { name: "Uruguay", iso2: "UY", code: "+598", flag: "🇺🇾", placeholder: "Phone number" },
  { name: "Uzbekistan", iso2: "UZ", code: "+998", flag: "🇺🇿", placeholder: "Phone number" },
  { name: "Vanuatu", iso2: "VU", code: "+678", flag: "🇻🇺", placeholder: "Phone number" },
  { name: "Vatican City", iso2: "VA", code: "+379", flag: "🇻🇦", placeholder: "Phone number" },
  { name: "Venezuela", iso2: "VE", code: "+58", flag: "🇻🇪", placeholder: "Phone number" },
  { name: "Vietnam", iso2: "VN", code: "+84", flag: "🇻🇳", placeholder: "Phone number" },
  { name: "Yemen", iso2: "YE", code: "+967", flag: "🇾🇪", placeholder: "Phone number" },
  { name: "Zambia", iso2: "ZM", code: "+260", flag: "🇿🇲", placeholder: "Phone number" },
  { name: "Zimbabwe", iso2: "ZW", code: "+263", flag: "🇿🇼", placeholder: "Phone number" },
];